training.set=./dataset/iFashion_UB/train.txt
test.set=./dataset/iFashion_UB/test.txt
dataset.name=iFashion_UB
model.name=LightGCN
model.type=graph
item.ranking=-topN 10,20,50
embbedding.size=64
num.max.epoch=25
batch_size=512
learnRate=0.001
reg.lambda=0.0005
LightGCN=-n_layer 2
output.setup=-dir ./results/
