training.set=./dataset/Youshu/train.txt
test.set=./dataset/Youshu/test.txt
dataset.name=Youshu
model.name=LightGCN
model.type=graph
seed=2024
item.ranking=-topN 10,20
embbedding.size=64
num.max.epoch=20
batch_size=1024
learnRate=0.002
reg.lambda=0.00001
LightGCN=-n_layer 1
output.setup=-dir ./results/
